version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
     - "80:3000"
    restart: always
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:Ab1234@postgres/TFE
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:latest
    container_name: next_postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "TFE"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_data:
